TEXT = {
    "title": {
        "main": "--- File Organizer ---"
    },
    "info": {
        "no_move_file": "移動対象のファイルが見つかりません。",
        "no_undo_file": "復元可能な履歴が見つかりません。",
        "create_default_config": "デフォルト設定でファイルを生成します。",
        "complete_create_config": "設定ファイルの生成が完了しました。",
        "check_config_and_rerun": "設定ファイルを確認し、再度実行してください。",
    },
    "success": {
        "load_config": "設定ファイルの読み込みに成功しました。",
        "move_complete": "{count} 個のファイルを移動しました。",
        "undo_complete": "{count} 個のファイルをUndoし、履歴をクリアしました。",
    },
    "confirm": {
        "move": "実行しますか？ (y,yesで実行): ",
        "undo": "Undoを実行しますか？ (y,yesで実行): ",
    },
    "cancel": {
        "move": "移動を中断しました。",
        "undo": "Undoを中断しました。",
    },
    "error": {
        "invalid_command": "{command} は無効なコマンドです。",
        "no_config_file": "設定ファイル ({CONFIG_FILE}) が見つかりません。",
        "move_failed": "{src} から {dst} への移動に失敗しました。",
        "read_history_failed": "履歴ファイルの読み込みに失敗しました: {error}",
        "save_history_failed": "履歴の保存に失敗しました: {error}",
        "delete_history_failed": "履歴ファイルの削除に失敗しました: {error}",
        "invalid_config": "設定ファイルのJSON形式が正しくありません: {error}",
        "generate_config_failed": "設定ファイルの生成に失敗しました: {error}",
        "read_config_failed": "設定ファイルの読み込みに失敗しました: {error}",
        "source_directory_required": "source_directory が指定されていません。",
        "dry_run_not_bool": "dry_run は boolean (true/false) である必要があります。",
        "source_dir_not_exist": "{source_directory} が存在しません。",
        "source_dir_not_dir": "{source_directory} がディレクトリではありません。",
        "rules_not_exist": "rules が存在しません。",
        "rules_not_list": "rules がリストではありません。",
        "extension_not_str": "extension が str ではありません。",
        "extension_must_start_with_dot": "extension が . で始まっていません。",
        "destination_required": "destination が存在しません。",
        "destination_not_str": "destination が str ではありません。",
        "duplicate_extension": "拡張子 '{extension}' は既に登録されています。",
        "ext_required": "拡張子を入力してください（例: .pdf）",
        "dest_required": "移動先フォルダを選択してください",
    },
        "gui": {
            "col_name": "ファイル名",
            "col_destination": "移動先フォルダ",
            "col_extension": "拡張子",
            "dialog_title_confirm": "確認",
            "dialog_move_confirm":"{count} 件のファイルの移動を実行しますか？",
            "dialog_undo_confirm":"ファイルの移動を元に戻しますか？",
            "tooltip_browse_dir": "フォルダを選択",
            "tooltip_move": "ファイルの移動",
            "tooltip_undo": "元に戻す",
            "tooltip_config_rules": "整頓ルールの編集",
            "tooltip_refresh": "表示内容の更新", 
            "path_label_default": "フォルダー: 未選択",
            "folder_display": "フォルダー: {path}",
            "filter_label": "拡張子フィルタ",
            "master_toggle_all": "すべて選択",
            "master_toggle_none": "すべて選択解除",
            "config_move_rule": "整頓ルールの編集",
            "config_window_title": "整頓ルールの編集",
            "footer_move_item_count": "移動予定: {move}/{total} ファイル",
            "footer_status_default": "ステータス: 起動完了",
            "footer_status_move_complate": "ステータス: 移動完了",
            "footer_status_undo_complete": "ステータス: 直前のファイル移動を巻き戻し完了",
            "footer_status_refresh_complete":"ステータス: 表示内容の更新完了",
            "footer_status_config_saved": "ステータス: 設定が保存されました",
            "footer_status_config_save_failed": "ステータス: 設定の保存に失敗しました",
            "footer_status_nothing_scaned_file": "ステータス: 対象フォルダに移動可能なファイルがありません",
            "footer_status_no_files_selected": "ステータス: 選択中のフィルタに一致するファイルがありません",
            "footer_status_nothing_undo_file": "ステータス: 元に戻せる移動履歴がありません",
            "footer_undo_available": "Undo: 可能",
            "footer_undo_unavailable": "Undo: 不可能",
            "cfg_remove_rule": "ルールを削除",
            "cfg_edit_rule": "選択項目を編集",
            "cfg_save_config": "設定を保存",
            "cfg_extension_example": "例: .jpg",
            "cfg_destination_example": "例: images/jpg",
            "cfg_browse_folder": "フォルダ参照...",
            "cfg_add_rule": "ルールを追加",
        },
}